config/routes.rb
Rails.application.routes.draw do

resources :midterms
root 'welcome#index'

resources :articles do
  resources :comments
end

end

app/models/comment.rb
class Article < ActiveRecord::Base
  has_many :comments
  validates :title, presence: true,
  length: { minimum: 5 }
end

app/models/midterm.rb
class Midterm < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/midterms_controller.rb
class MidtermsController < ApplicationController
  before_action :set_midterm, only: [:show, :edit, :update, :destroy]

  # GET /midterms
  # GET /midterms.json
  def index
    @midterms = Midterm.all
  end

  # GET /midterms/1
  # GET /midterms/1.json
  def show
  end

  # GET /midterms/new
  def new
    @midterm = Midterm.new
  end

  # GET /midterms/1/edit
  def edit
  end

  # POST /midterms
  # POST /midterms.json
  def create
    @midterm = Midterm.new(midterm_params)

    respond_to do |format|
      if @midterm.save
        format.html { redirect_to @midterm, notice: 'Midterm was successfully created.' }
        format.json { render :show, status: :created, location: @midterm }
      else
        format.html { render :new }
        format.json { render json: @midterm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /midterms/1
  # PATCH/PUT /midterms/1.json
  def update
    respond_to do |format|
      if @midterm.update(midterm_params)
        format.html { redirect_to @midterm, notice: 'Midterm was successfully updated.' }
        format.json { render :show, status: :ok, location: @midterm }
      else
        format.html { render :edit }
        format.json { render json: @midterm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /midterms/1
  # DELETE /midterms/1.json
  def destroy
    @midterm.destroy
    respond_to do |format|
      format.html { redirect_to midterms_url, notice: 'Midterm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_midterm
      @midterm = Midterm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def midterm_params
      params.require(:midterm).permit(:Title, :text)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/midterms_helper.rb
module MidtermsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mtblog2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/midterms/_form.html.erb
<%= form_for(@midterm) do |f| %>
  <% if @midterm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@midterm.errors.count, "error") %> prohibited this midterm from being saved:</h2>

      <ul>
      <% @midterm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Title %><br>
    <%= f.text_field :Title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/midterms/edit.html.erb
<h1>Editing midterm</h1>

<%= render 'form' %>

<%= link_to 'Show', @midterm %> |
<%= link_to 'Back', midterms_path %>

app/views/midterms/index.html.erb
<h1>Listing midterms</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @midterms.each do |midterm| %>
      <tr>
        <td><%= midterm.Title %></td>
        <td><%= midterm.text %></td>
        <td><%= link_to 'Show', midterm %></td>
        <td><%= link_to 'Edit', edit_midterm_path(midterm) %></td>
        <td><%= link_to 'Destroy', midterm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Midterm', new_midterm_path %>

app/views/midterms/new.html.erb
<h1>New midterm</h1>

<%= render 'form' %>

<%= link_to 'Back', midterms_path %>

app/views/midterms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @midterm.Title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @midterm.text %>
</p>

<%= link_to 'Edit', edit_midterm_path(@midterm) %> |
<%= link_to 'Back', midterms_path %>

app/views/welcome/index.html.erb
<h1>Welcome to my Midterm Ruby App</h1>

<%= link_to 'Ruby App', controller: 'midterms' %>